version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo_crm
    restart: always
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_crm
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
